### ISSUE TITLE
New feature: eigensolver using Block Davidson algorithm.

### ISSUE THREAD

**Issue by ddagson** [dftworks/dftworks#4]
### Task
- [ ] Implement _Block Davidson_-algorithm using the interface of the `trait EigenSolver`.
    1. [ ] Define `struct` for computation (Compare to EigenSolverPCG?)
    2. [ ] Implement algorithm and trait
    3. [ ] Add unit tests 

### Potential Clarifications
- [ ]  Pinpoint specific version of algorithm

### References
...
